22.06.2021/backend/Add bot_server
future-code-lab/botnet pull request #23
Opened 2021-06-22 18:15 UTC by Uzhastin-Nikita

2021-06-22 22:54 UTC, Zimtir commented on development/backend/bot_server.py
> +
Убери эти пустые строки

2021-06-22 22:54 UTC, Zimtir commented on development/backend/bot_server.py
> +        pass
Давай классы в отдельные файлы

2021-06-22 22:55 UTC, Zimtir commented on development/backend/bot_server.py
> +
текущий файл перенеси в папку `bot` лучше

2021-06-22 22:59 UTC, Zimtir commented on development/backend/bot_server.py
> +    while(flag == True):
плохая идея

2021-06-23 09:37 UTC, Uzhastin-Nikita commented on development/backend/bot_server.py
> +    while(flag == True):
я хотел сделать, что, если Пользователь пишет "Пока", то значение flag = False и цикл завершается

2021-06-23 10:55 UTC, egordunaev commented on development/backend/bot_server.py
> +    while(flag == True):
Распиши по конкретней что именно это за флаг, например `active_session_flag`, просто flag не совсем понятно

2021-06-23 13:27 UTC, egordunaev reviewed
Нужно добавить еще `.gitignore` на `__pycache__` и `.vscode` папки, чтобы они не трекались

2021-06-23 13:27 UTC, egordunaev commented on development/bot/server.py
> +
Возможно архитектурный вопрос (@Zimtir) но не стоит ли здесь тоже сделать класс Server?

2021-06-23 13:27 UTC, egordunaev commented on development/bot/server.py
> +    while (active_session_flag == True):
Можно просто `while (active_session_flag):`

2021-06-23 15:16 UTC, Zimtir commented on development/bot/server.py
> +
если хочешь ООП, тогда да всё верно

@egordunaev @Uzhastin-Nikita

2021-06-23 15:17 UTC, Zimtir requested changes

2021-06-23 15:17 UTC, Zimtir commented on development/bot/bot.py
> +        print(f'Bot: {self.message}')
Добавь пустую строку. в конце файла

2021-06-23 15:17 UTC, Zimtir commented on development/bot/server.py
> +main()
Добавь пустую строку. в конце файла

2021-06-23 17:43 UTC, Uzhastin-Nikita commented on development/bot/server.py
> +
@egordunaev и что в классе Server должно быть?

2021-06-23 19:58 UTC, egordunaev commented on development/bot/server.py
> +
Пока не знаю, поэтому и думал что это архитектурный вопрос 😃  , но думаю это к Марату, а так пока что сойдет.

2021-06-23 20:23 UTC, Uzhastin-Nikita commented
Друзья мои, я попытался реализовать паттерн Адаптер, пожалуйста, не смейтесь сильно надо мной :)

2021-06-23 20:48 UTC, Zimtir commented on development/bot/bot.py
> +
```suggestion

```

2021-06-23 20:48 UTC, Zimtir commented on development/bot/bot.py
> +
```suggestion

```

2021-06-23 20:49 UTC, Zimtir commented on development/bot/server.py
> +
```suggestion

```

2021-06-23 20:50 UTC, Zimtir commented on development/bot/server.py
> +main()
```suggestion

main()
```

2021-06-23 20:51 UTC, Zimtir commented on development/bot/bot.py
> +
```suggestion
```

2021-06-23 20:51 UTC, Zimtir commented on development/bot/bot.py
> +
```suggestion
```

2021-06-23 20:51 UTC, Zimtir approved these changes

2021-06-23 21:11 UTC, merged

2021-10-08 23:29 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: