BS - Docker
future-code-lab/botnet pull request #26
Opened 2021-06-26 01:16 UTC by egordunaev

Adding CI/CD for the project

2021-06-29 18:30 UTC, Zimtir requested changes

2021-06-29 18:30 UTC, Zimtir commented on .github/workflows/python-package.yml
> +    branches: [ master ]
```suggestion
  push:
  pull_request:
    branches: [ master ]
```

2021-06-29 18:30 UTC, Zimtir commented on .github/workflows/python-package.yml
> +    - name: Install dependencies
```suggestion

    - name: Install dependencies
```

2021-06-29 18:30 UTC, Zimtir commented on .github/workflows/python-package.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@v2

```

2021-06-29 18:30 UTC, Zimtir commented on .github/workflows/python-package.yml
> +    - name: Lint with flake8
```suggestion

    - name: Lint with flake8
```

2021-06-29 18:30 UTC, Zimtir commented on development/.gitignore
> +cython_debug/
```suggestion
cython_debug/

```

2021-07-09 21:51 UTC, Zimtir commented
@egordunaev should we do something extra here before merge? I think we should move it forward

Does it make sense?

2021-07-10 14:48 UTC, egordunaev commented
> @egordunaev should we do something extra here before merge? I think we should move it forward
> 
> Does it make sense?

@Zimtir 
I wanted to finish this checklist before merge, or is this PR needs to be complete ASAP? (Sorry for the delay)

2021-07-10 19:02 UTC, Zimtir commented
> > @egordunaev should we do something extra here before merge? I think we should move it forward
> > Does it make sense?
> 
> @Zimtir
> I wanted to finish this checklist before merge, or is this PR needs to be complete ASAP? (Sorry for the delay)

I think we can avoid finishing the checklist because it can so long, but the current code can be used now

2021-07-10 19:03 UTC, egordunaev commented
> > > @egordunaev should we do something extra here before merge? I think we should move it forward
> > > Does it make sense?
> > 
> > 
> > @Zimtir
> > I wanted to finish this checklist before merge, or is this PR needs to be complete ASAP? (Sorry for the delay)
> 
> I think we can avoid finishing the checklist because it can so long, but the current code can be used now

Would it be better if we made another task for this?

2021-07-10 22:16 UTC, Zimtir commented
> > > > @egordunaev should we do something extra here before merge? I think we should move it forward
> > > > Does it make sense?
> > > 
> > > 
> > > @Zimtir
> > > I wanted to finish this checklist before merge, or is this PR needs to be complete ASAP? (Sorry for the delay)
> > 
> > 
> > I think we can avoid finishing the checklist because it can so long, but the current code can be used now
> 
> Would it be better if we made another task for this?

Could you make issues here?
https://github.com/future-code-lab/botnet/issues

2021-07-13 20:49 UTC, egordunaev commented
@Zimtir PTAL 🥺 🙏

2021-07-15 15:35 UTC, Zimtir approved these changes
LGTM with small suggestions

2021-07-15 18:43 UTC, Zimtir commented on development/docker-compose.yml
> +
```suggestion

```

2021-07-15 18:43 UTC, Zimtir approved these changes

2021-07-15 18:43 UTC, Zimtir commented
🐰

2021-07-15 18:47 UTC, merged