Addition dialog bot
future-code-lab/botnet pull request #28
Opened 2021-07-03 17:52 UTC by Uzhastin-Nikita

2021-07-09 21:50 UTC, Zimtir commented
@egordunaev could you review and finish it?

2021-07-10 15:53 UTC, egordunaev requested changes

2021-07-10 15:53 UTC, egordunaev commented on development/bot/bot.py
> +        """data for dialog"""
Что из себя представляет `data for dialog`? Набор пользовательских команд? Обозначь как-то понятнее.

Если это команды вызова, не легче ли пока ограничиться по одной команде, чтобы четко разделить что мы хотим от бота, например вместо `привет` использовать какой-нибудь `/hello`? Или у нас планируется распознание смысла из сообщения?

2021-07-10 15:53 UTC, egordunaev commented on development/bot/bot.py
> +        else:
Можно без `else`, если предыдущие не выполнились то мы в любом случае сюда придем.

2021-07-10 15:53 UTC, egordunaev commented on development/bot/bot.py
> +        if message in farewell_message:
Если у нас сообщение с прощанием, может тогда и `active_session_flag` заменим на `False`, чтобы бот прекратил работу?

2021-07-10 16:22 UTC, egordunaev commented
Не забудь еще зарезолвить мердж конфликты 💡

2021-07-10 19:01 UTC, Uzhastin-Nikita commented on development/bot/bot.py
> +        """data for dialog"""
Скорее распознание смысла из сообщения

2021-07-10 19:35 UTC, Uzhastin-Nikita commented on development/bot/bot.py
> +        if message in farewell_message:
Я думаю, может нам вообще убрать active_session_flag?

2021-07-10 21:39 UTC, egordunaev reviewed
Добавь ко всем ответам от бота обозначение что это бот, можно так же обозначить пользователя чтобы выглядело как-то так:
```
Вы: привет
Bot: Привет!
```

2021-07-10 22:22 UTC, Uzhastin-Nikita commented
А в реалиях вк, телеграмма это нормально будет выглядеть?

2021-07-10 22:52 UTC, egordunaev commented
> А в реалиях вк, телеграмма это нормально будет выглядеть?
> Если чисто консоль, то да, интересно и прикольно

Если с вк и телеграммом тогда **looks good**. 🚀

2021-07-10 22:53 UTC, egordunaev approved these changes

2021-07-10 22:58 UTC, merged

2021-10-08 23:29 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: