BS - Telegram
future-code-lab/botnet pull request #32
Opened 2021-07-22 16:43 UTC by Uzhastin-Nikita

2021-07-22 18:06 UTC, egordunaev requested changes

2021-07-22 18:06 UTC, egordunaev commented on development/README.md
> -- [VirtualBox](https://www.virtualbox.org)
А почему удаляем этот файл?

2021-07-22 18:07 UTC, egordunaev commented
@Zimtir PTAL

2021-07-22 18:08 UTC, Uzhastin-Nikita commented on development/telegram/server.py
> +        message = message.replace('?', '')
Я до этого делал через цикл, но с циклом не работает почему-то

2021-07-22 18:09 UTC, Uzhastin-Nikita commented on development/README.md
> -- [VirtualBox](https://www.virtualbox.org)
прости... :(

2021-07-23 08:04 UTC, Zimtir commented on development/README.md
> -- [VirtualBox](https://www.virtualbox.org)
git revert и номер коммита

2021-07-23 08:05 UTC, Zimtir commented on development/README.md
> -- [VirtualBox](https://www.virtualbox.org)
или что-то вроде get checkout origin README.md

2021-07-23 10:25 UTC, egordunaev commented on development/telegram/server.py
> +        message = message.replace('?', '')
Ну тут способов так-то море как это можно сделать. 

Да, можно через циклы. Можно еще через `regex` попробовать. Либо через вложенный `replace().replace()...`. Посмотри, способов много, подбери который лучше подходит.

2021-07-23 10:37 UTC, Uzhastin-Nikita commented on development/telegram/server.py
> +        message = message.replace('?', '')
`replace().replace()...` мне больше нравится

2021-07-23 10:53 UTC, egordunaev commented on development/telegram/server.py
> +        message = message.replace('?', '')
[Здесь](https://stackoverflow.com/questions/3411771/best-way-to-replace-multiple-characters-in-a-string) описывается довольно много примеров как это можно сделать. Pick your favourite ☺️

2021-07-23 11:25 UTC, egordunaev requested changes

2021-07-23 11:25 UTC, egordunaev commented on development/telegram/bot.py
> +        """data for dialog: recognizing meaning from messages"""
У тебя везде комментирование кода пишется по-разному.
То с `"""` то с `#`. Систематизируй пожалуйста, чтобы комментарии были одинаковы по стилю.

2021-07-23 11:25 UTC, egordunaev commented on development/telegram/bot.py
> +        context = []
Разве не получится что мы сохраняем контекст внутри метода? Не лучше ли сделать `self.context`?

2021-07-23 11:25 UTC, egordunaev commented on development/telegram/server.py
> +        message = message.replace('.', '').replace(',', '').replace('?', '').replace('!', '').replace('.', '').replace(':', '').replace(' ', '')
Мне кажется что обработку сообщения и контекста можно убрать в бота.

2021-07-23 11:25 UTC, egordunaev commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
А что именно за токен?

2021-07-23 11:28 UTC, Uzhastin-Nikita commented on development/telegram/bot.py
> +        """data for dialog: recognizing meaning from messages"""
Идея была в том, что типо есть заголовки, а есть пояснения. 

Вопрос: есть ли различия в конструкциях или просто на усмотрения пользователя?

2021-07-23 11:30 UTC, Uzhastin-Nikita commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
Его нужно в gitignore добавить. Он у меня на ноуте сейчас локально лежит, если мы его зальем на гит, то любой сможет получить доступ к настройкам нашего бота

2021-07-23 11:34 UTC, Uzhastin-Nikita commented on development/telegram/bot.py
> +        context = []
Не понял, можно подробнее пожалуйста?

2021-07-23 11:36 UTC, Uzhastin-Nikita commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
У каждого бота есть свой Токен, который мы получаем при регистрации нашего бота в BotFarher, я сделал его Переменной окружения с помощью dotenv

2021-07-23 11:38 UTC, egordunaev commented on development/telegram/bot.py
> +        """data for dialog: recognizing meaning from messages"""
По сути `#` позволяет писать строчные комментарии, в одну строку, и даже в той строке где есть код, например:
```python
# Комментарий
print("Hello, World!")

# Комментарий
# и здесь тоже комментарий
print("Hello world") # Тоже комментарий
```

А `"""` считывается питоном как строка без присвоенной к ней переменной, поэтому питон при компиляции ее игнорит, соответственно можно использовать как многострочный комментарий, например:
```python
"""
Комментарий
Который написан
на нескольких строчках
"""
print("Hello, World!")
```

Все что мне хотелось, это видеть единый стиль комментирования, особенно учитывая что у тебя все комментарии в одну строку. Выбирай какой тебе удобен, но старайся придерживаться одного единого стиля.

2021-07-23 11:39 UTC, Uzhastin-Nikita commented on development/telegram/bot.py
> +        """data for dialog: recognizing meaning from messages"""
Хорошо, большое спасибо за пояснение. 

Уже всё изменил на #

2021-07-23 11:41 UTC, Uzhastin-Nikita commented on development/telegram/bot.py
> +        context = []
Просто сделать` self.context = []` ?

2021-07-23 11:43 UTC, egordunaev commented on development/telegram/bot.py
> +        context = []
Ну да. Я имел ввиду что можно хранить контекст сообщения внутри класса, нежели просто в переменной.

2021-07-23 11:47 UTC, egordunaev commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
Мой вопрос был больше про конкретизацию в коде, если от телеграмма то напиши лучше `TELEGRAM_TOKEN`, у нас же будут и другие токены в будущем.

2021-07-23 11:48 UTC, egordunaev commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
Что касательно `.env` файла я не знаю точно как тут лучше поступить. Я бы предложил залить пустой `.env` файл, отдельным коммитом добавить его в гит игнор и в будущем можем просто автоматизировать стягивание Secret'ов с репозитория. @Zimtir Как тут лучше поступить?

2021-07-23 12:33 UTC, egordunaev approved these changes

2021-07-23 12:45 UTC, egordunaev approved these changes

2021-07-25 00:12 UTC, Zimtir commented on development/telegram/settings.py
> +TOKEN = os.getenv("TOKEN")
можно сделать проверку на наличие этого файла, в репозитории хранить template.env с примерным заполнением, в CI записать каст template.env в .env чтобы тесты не падали

2021-07-25 12:22 UTC, Uzhastin-Nikita commented
merge? Проверку на exist-файла сделал

2021-07-25 12:23 UTC, Uzhastin-Nikita commented
merge?

2021-07-25 12:42 UTC, merged

2021-10-08 23:29 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: