BS - Flask
future-code-lab/botnet pull request #35
Opened 2021-07-25 18:52 UTC by Uzhastin-Nikita

2021-07-25 18:53 UTC, Uzhastin-Nikita commented
Простите, но это всё, что у меня получилось сделать. 
Не работает диалоговое окно

2021-07-27 18:22 UTC, egordunaev requested changes
Хотел стянуть ветку и запустить посмотреть твои изменения но заметил что ты делаешь это не в отдельной ветке а в форке, почему?

2021-07-27 18:22 UTC, egordunaev commented on development/flask/bot.py
> +class Bot:
Разве этот файл не в #34 ?

2021-07-27 18:22 UTC, egordunaev commented on development/flask/bot.py
> +class Bot:
Разве этот файл не в #34 ?

2021-07-27 18:22 UTC, egordunaev commented on development/flask/app.py
> +    return render_template("index.html")
`index.html`? А расскажи по подробнее зачем нам эта страница? Разве сервер не должен выступать здесь как точка обработки сообщений с вк/телеграмма?

2021-07-27 18:22 UTC, egordunaev commented on development/flask/server.py
> +from bot import Bot
То же самое что и выше, разве это не в PR #34 ?

2021-07-27 18:23 UTC, egordunaev commented on development/flask/bot.py
> +class Bot:
Сори продублировал, my bad.

2021-07-27 18:53 UTC, Uzhastin-Nikita commented
надо бы всё сделать с нуля

2021-07-27 21:31 UTC, Uzhastin-Nikita commented
> Хотел стянуть ветку и запустить посмотреть твои изменения но заметил что ты делаешь это не в отдельной ветке а в форке, почему?

Я всегда через форк делаю? :-)

2021-08-05 12:09 UTC, closed without merging