BS - VKontakte
future-code-lab/botnet pull request #37
Opened 2021-08-13 12:20 UTC by Uzhastin-Nikita

2021-08-13 12:22 UTC, Uzhastin-Nikita commented
В общем. Как я решил сделать.
Есть папка base, где лежит вся "начинка", после этого мы создаем файл, например, vk.py, задействуем в нём нужные нам функции. 
У меня возникает проблема с импортами файлов, помогите разобраться :(

2021-08-14 11:09 UTC, Uzhastin-Nikita commented
Всё, я разобрался с проблемой.

2021-08-17 05:55 UTC, Uzhastin-Nikita commented
@egordunaev finish him

2021-08-23 22:39 UTC, Zimtir requested changes

2021-08-23 22:39 UTC, Zimtir commented on development/.env
> +BOT_NAME=Nikita
Add the empty line at end of file

2021-08-23 22:39 UTC, Zimtir commented on development/base/bot.py
> +        self.context.append(message)
Add the empty line at end of file

2021-08-23 22:39 UTC, Zimtir commented on development/vk.py
> +            write_message(event.user_id, server.Server(event.text))
Add the empty line at end of file

2021-08-23 22:39 UTC, Zimtir commented on development/base/settings.py
> +    BOT_NAME = os.getenv("BOT_NAME")
Add the empty line at end of file

2021-08-23 22:39 UTC, Zimtir commented on development/base/server.py
> +        return bot.dialog(message)
Add the empty line at end of file

2021-08-23 22:39 UTC, Zimtir commented on development/base/server.py
> +    while(True):
Should we avoid the infinity loop?

2021-08-23 22:39 UTC, Zimtir commented on development/base/bot.py
> +class Bot:
Could you add the unit testing?

https://habr.com/ru/company/otus/blog/481806/
https://pythonworld.ru/moduli/modul-unittest.html

2021-08-23 22:39 UTC, Zimtir commented on development/base/bot.py
> +        # dialog
what's code for the comment?

2021-08-23 22:39 UTC, Zimtir commented on development/vk.py
> +        if event.to_me:
Let's merge into one condition instead two?

2021-08-23 22:51 UTC, egordunaev requested changes

2021-08-23 22:51 UTC, egordunaev commented on development/base/bot.py
> +        condolences_message = ['мнетебяжаль', 'ятебесочуствую', 'тысправишься', 'ятебесожалею', 'сожалею', 'соболезную', 'жаль', 'жальтебя']
Думаю что это лучше вынести в конфиг

2021-08-23 22:51 UTC, egordunaev commented on development/base/bot.py
> +        return 'Я вас не понимаю'
Ответы бота тоже лучше думаю в конфиг

2021-08-24 08:38 UTC, Uzhastin-Nikita commented on development/base/bot.py
> +        condolences_message = ['мнетебяжаль', 'ятебесочуствую', 'тысправишься', 'ятебесожалею', 'сожалею', 'соболезную', 'жаль', 'жальтебя']
В .env или settings.py ?

2021-08-24 08:49 UTC, Uzhastin-Nikita commented on development/base/server.py
> +    while(True):
для вк и телеги от цикла вообще можно избавится, потому что мы и там и там заранее создаем циклы, а вот для simple_chat придется сделать просто отдельный файлик simple_chat.py

2021-09-05 10:23 UTC, Uzhastin-Nikita commented on development/base/bot.py
> +        condolences_message = ['мнетебяжаль', 'ятебесочуствую', 'тысправишься', 'ятебесожалею', 'сожалею', 'соболезную', 'жаль', 'жальтебя']
@egordunaev у меня в планах вообще прикручивать какую-нибудь нейронку на ответы, стоит выносить в конфиг или пока оставим?

2021-09-05 10:57 UTC, closed without merging