DS-4: Component library
future-code-lab/botnet pull request #38
Opened 2021-09-04 23:33 UTC by Zimtir

- Add a basic project that closes #$

2021-09-05 15:26 UTC, Proza1k requested changes
также думаю стоит добавить .prettier конфиг для формата документов

2021-09-05 15:26 UTC, Proza1k commented on development/components/.gitignore
> +yarn-error.log*
add empty line

2021-09-05 15:26 UTC, Proza1k commented on development/components/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
update file description

2021-09-05 15:26 UTC, Proza1k commented on development/components/.storybook/main.js
> +const path = require('path');
is there a setting for typescript?

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/components/Button.tsx
> +   * Simple click handler
remove please comments

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/components/Button.tsx
> + * The world's most _basic_ button
same

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/index.tsx
> +// If you want your app to work offline and load faster, you can change
remove please comments

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Is this file being used somewhere? If not, then delete

2021-09-05 15:26 UTC, Proza1k commented on development/components/package.json
> +    "eject": "react-scripts eject",
Может стоит добавить eslint сюда?

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/serviceWorker.ts
> +// opt-in, read https://bit.ly/CRA-PWA
remove comments please

2021-09-05 15:26 UTC, Proza1k commented on development/components/src/setupTests.ts
> +// learn more: https://github.com/testing-library/jest-dom
remove please comments

2021-09-05 15:30 UTC, Zimtir commented on development/components/package.json
> +    "eject": "react-scripts eject",
Add an issue into list of backlog

2021-09-11 15:40 UTC, Proza1k requested changes

2021-09-11 15:40 UTC, Proza1k commented on development/components/.editorconfig
> +# http://EditorConfig.org
remove comment

2021-09-11 15:40 UTC, Proza1k commented on development/components/.eslintrc.json
> +{
format code

2021-09-11 15:40 UTC, Proza1k commented on development/components/.gitignore
> +yarn-error.log*
add empty line

2021-09-11 15:40 UTC, Proza1k commented on development/components/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
please update information readme

2021-09-11 15:40 UTC, Proza1k commented on development/components/public/index.html
> +    -->
remove comments

2021-09-11 15:40 UTC, Proza1k commented on development/components/public/index.html
> +    -->
```suggestion
```

2021-09-11 15:40 UTC, Proza1k commented on development/components/public/index.html
> +    -->
```suggestion
```

2021-09-11 15:41 UTC, Proza1k commented on development/components/.gitignore
> +yarn-error.log*
```suggestion
yarn-error.log*

package-lock.json
yarn.lock
```

2021-09-11 17:12 UTC, Proza1k approved these changes

2021-09-12 07:25 UTC, merged

2021-10-08 23:29 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: