BS - Bot
future-code-lab/botnet pull request #39
Opened 2021-09-05 10:55 UTC by Uzhastin-Nikita

Решил немного изменить структуру. Теперь есть папка base, откуда просто достаем нужные файлы.

2021-09-05 10:55 UTC, Uzhastin-Nikita commented
Только надо ещё удалить с master ненужные файлы будет

2021-09-05 15:29 UTC, Zimtir requested changes

2021-09-05 15:29 UTC, Zimtir commented on development/.env
> +BOT_NAME=Nikita
I think we should remove the right side and write about the filling and links at Readme

```suggestion
TELEGRAM_TOKEN=
VK_TOKEN=
BOT_NAME=
```

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +        message = message.replace('.', '').replace(',', '').replace('?', '').replace('!', '').replace('.', '').replace(':', '').replace(' ', '')
let's move the right side into the separated function

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +        message = message.lower()
let's move the right side into the separated function

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +        greeting_message = ['привет', 'доброеутро', 'добрыйдень', 'добрыйвечер', 'здравствуй', 'здравствуйте', 'приветствую', 'прив', 'здрасти', 'ктоты', 'тыкто']
let's move to the constant

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +        condolences_message = ['мнетебяжаль', 'ятебесочуствую', 'тысправишься', 'ятебесожалею', 'сожалею', 'соболезную', 'жаль', 'жальтебя']
let's move to the constants outside of the function

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +        return 'Я вас не понимаю'
let's move into the separated functions

2021-09-05 15:29 UTC, Zimtir commented on development/base/bot.py
> +
```suggestion

```

2021-09-05 15:29 UTC, Zimtir commented on development/base/server.py
> +
```suggestion

```

2021-09-05 15:29 UTC, Zimtir commented on development/base/settings.py
> +
```suggestion

```

2021-09-05 15:29 UTC, Zimtir commented on development/telegram.py
> +bot.polling(none_stop = True)
```suggestion
bot.polling(none_stop = True)

```

2021-09-05 15:29 UTC, Zimtir commented on development/vk.py
> +
```suggestion

```

2021-09-05 17:32 UTC, Uzhastin-Nikita commented on development/base/bot.py
> +        message = message.replace('.', '').replace(',', '').replace('?', '').replace('!', '').replace('.', '').replace(':', '').replace(' ', '')
вынести в отдельную функцию?

2021-09-06 19:55 UTC, Uzhastin-Nikita commented on development/base/bot.py
> +        greeting_message = ['привет', 'доброеутро', 'добрыйдень', 'добрыйвечер', 'здравствуй', 'здравствуйте', 'приветствую', 'прив', 'здрасти', 'ктоты', 'тыкто']
@Zimtir в питоне есть константы?

2021-09-15 09:46 UTC, Uzhastin-Nikita commented
@Zimtir       finish him

2021-09-15 19:30 UTC, egordunaev requested changes
Посмотрел PR, не совсем пойму почему тут дубликация кода происходит и почему `__init__` файлы пустые?

2021-09-15 19:30 UTC, egordunaev commented on development/telegram.py
> +import base.settings as sett
Why `sett`? Can't you just name it as `settings`?

2021-09-15 19:30 UTC, egordunaev commented on development/base/bot.py
> +            return 'Спасибо, мне очень приятно :)'
Can we move Bot answers to another file?
I think bot answers should be in txt or csv file and add some kind of python parser to insert bot answers in `return`.
Basically approach would be the same as with settings and `.env` file

2021-09-15 19:30 UTC, egordunaev commented on development/bot/base/bot.py
> +            return 'Спасибо, мне очень приятно :)'
Remind me why do we duplicate alot of code here? Isn't it the same as in `development/base/bot.py`?

2021-09-30 17:42 UTC, Uzhastin-Nikita commented
@egordunaev
@Zimtir 
Нужно будет из мастера удалить папку telegram

2021-10-02 08:06 UTC, Zimtir requested changes

2021-10-02 08:06 UTC, Zimtir commented on development/base/prepare_message.py
>      return message
Добавь пустую строку в конце файла

2021-10-02 08:06 UTC, Zimtir commented on development/base/settings.py
> +    DIFFERENT_MESSAGE = os.getenv("DIFFERENT_MESSAGE")
Добавь пустую строку в конце файла

2021-10-02 08:06 UTC, Zimtir commented on development/tests.py
> +import os
почему в корне development? 
у нас там как бы еще проекты лежат

2021-10-02 08:08 UTC, Zimtir requested changes

2021-10-02 08:08 UTC, Zimtir commented on development/bot/base/prepare_message.py
> +    return message
Добавь пустую строку в конце файла

2021-10-02 08:08 UTC, Zimtir commented on development/bot/.env
> +DIFFERENT_MESSAGE=Я вас не понимаю :(
Добавь пустую строку в конце файла

2021-10-02 08:08 UTC, Zimtir commented on development/bot/base/bot.py
> +        self.context.append(message)
Добавь пустую строку в конце файла

2021-10-02 08:08 UTC, Zimtir commented on development/bot/base/server.py
> +    return bot.dialog(message)
Добавь пустую строку в конце файла

2021-10-02 08:08 UTC, Zimtir commented on development/bot/base/settings.py
> +    DIFFERENT_MESSAGE = os.getenv("DIFFERENT_MESSAGE")
Добавь пустую строку в конце файла

2021-10-02 08:16 UTC, Uzhastin-Nikita commented
@Zimtir можно делать merge?

2021-10-02 11:35 UTC, Zimtir approved these changes

2021-10-02 11:36 UTC, merged

2021-10-08 23:29 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: