DS-43/card
future-code-lab/botnet pull request #44
Opened 2021-09-26 20:53 UTC by Zimtir

- Arrange

![image](https://user-images.githubusercontent.com/32175240/134823715-4978d8fe-22cc-48e6-a221-ff8369431c61.png)

- Acceptance criteria:
  - [x] - React component
  - [x] - TypeScript
  - [x] - Module SCSS
  - [x] - Tests
  - [x] - Fixtures
  - [ ] - Stories
  - [x] - Exporting
  - [x] - Pixel perfect
  - [ ] - Mobile
  - [ ] - Tablet
  - [ ] - Desktop

2021-09-26 20:56 UTC, Zimtir commented on development/components/src/components/Card/Card.tsx
> +      )}w
Remove `w`

```suggestion
      )}
```

2021-09-26 20:56 UTC, Zimtir commented on development/components/src/components/Card/Card.tsx
> +  children?: ReactNode | string;
Add the type for `ReactNode | string`

2021-09-26 20:56 UTC, Zimtir commented on development/components/src/components/Card/Card.tsx
> +  withButton,
Define reason to use flags `with` at Readme.md

2021-09-26 20:56 UTC, Zimtir commented on development/components/src/components/Container/fixture.tsx
> +export const ChildrenFixtureComponent = <div>Hello world</div>;
Move to the global

2021-09-26 21:32 UTC, Proza1k requested changes

2021-09-26 21:32 UTC, Proza1k commented on development/components/src/components/Card/Card.module.scss
> +.card {
Посидел и подумал - может придумаем какие-нибудь глобальные переменные :root по типу:
`
--button-font-size: 16px;
`

2021-09-26 21:32 UTC, Proza1k commented on development/components/src/components/Card/Card.test.tsx
> +});
Спасибо за тесты!

2021-09-26 21:32 UTC, Proza1k commented on development/components/src/components/Card/Card.tsx
> +      )}w
Удали w

2021-09-26 21:32 UTC, Proza1k commented on development/components/src/components/Card/fixture.tsx
> +export const propsFixtureFullComponentChildren: CardProps = {
Чем отличаются эти пропсы от выше указанных?

2021-09-26 21:34 UTC, Zimtir commented on development/components/src/components/Card/fixture.tsx
> +export const propsFixtureFullComponentChildren: CardProps = {
Хочу иметь тесты для разного поведения пропсов, посмотри на snapshots

2021-09-29 17:45 UTC, Zimtir commented on development/components/src/components/Card/Card.module.scss
> +.card {
Сделай тикет плиз

2021-10-05 17:58 UTC, merged

2021-10-08 23:28 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/future-code-lab/botnet/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: